typography_spectrum: 0.13867369550280273
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18299559643492103
  lightness: 0.6943112201988697
  saturation: 0.09395392262376845
  rhythmicContrast: 0.91204873053357
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.831392667023465
analytics:
  google: null
  facebook: null
  twitter: null
name: Arteriorcept
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: This is the tag line
purpose: []
